In [1]:
# 1️⃣  Load Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

In [2]:
# Load Data
gscpi = pd.read_excel("gscpi_data.xls", sheet_name="Data", parse_dates=True)
wb_stress = pd.read_excel("Stress index tables.xlsx", sheet_name="global", parse_dates=True)

# Inspect
print(gscpi.head())
print(wb_stress.head())

          Date     GSCPI
0  31-Jan-1998 -1.082835
1  28-Feb-1998 -0.446144
2  31-Mar-1998 -0.066519
3  30-Apr-1998 -0.124812
4  31-May-1998 -0.429407
  Departure_YearMonth  delayed_capacity
0          2025-09-01      1.743273e+06
1          2025-08-01      1.795257e+06
2          2025-07-01      1.738896e+06
3          2025-06-01      1.715880e+06
4          2025-05-01      1.677112e+06

In [3]:
gscpi.Date = pd.to_datetime(gscpi.Date)

In [4]:
wb_stress.Departure_YearMonth = pd.to_datetime(wb_stress.Departure_YearMonth, format="%Y%m%d")

In [7]:
gscpi.columns = ["Date", "GSCPI"]
wb_stress.columns = ["Date", "WB_Stress"]
wb_stress = wb_stress.set_index("Date")
data_nearest = pd.merge_asof(
    gscpi.sort_values("Date"), 
    wb_stress.sort_index(), 
    on="Date", 
    direction="nearest", 
    tolerance=pd.Timedelta("30D")
)
data_nearest.head()

        Date     GSCPI  WB_Stress
0 1998-01-31 -1.082835        NaN
1 1998-02-28 -0.446144        NaN
2 1998-03-31 -0.066519        NaN
3 1998-04-30 -0.124812        NaN
4 1998-05-31 -0.429407        NaN

In [5]:
# Clean & Align
gscpi.columns = ["Date", "GSCPI"]
wb_stress.columns = ["Date", "WB_Stress"]
data = pd.merge(gscpi, wb_stress, on="Date", how="inner").sort_values("Date")

In [6]:
data.head()

Empty DataFrame
Columns: [Date, GSCPI, WB_Stress]
Index: []

In [ ]:

# 5️⃣  Visualize
sns.lineplot(data=data, x="Date", y="GSCPI", label="NY Fed GSCPI")
sns.lineplot(data=data, x="Date", y="WB_Stress", label="World Bank Stress")
plt.title("Global Supply Chain Stress Indices Over Time")
plt.show()

# 6️⃣  Summary Stats
print(data.describe())
data.corr()

# 7️⃣  (Later) Merge Insurance / Loss Data
# claims = pd.read_csv("LossRatios.csv")
# data = pd.merge(data, claims, on="Date", how="inner")

# 8️⃣  R

In [3]:
r = [1,2,3,4,5,6]
P = 6000
ans = []
for val in r:
    ans.append(P*(1 + (val/1200))**72)

In [4]:
ans

[6370.860094209962,
 6764.305395840313,
 7181.69080519837,
 7624.451274474795,
 8094.106464952466,
 8592.26567094986]

In [2]:
sri = pd.read_csv("swissre_insurance.csv")

In [3]:
sri.head()

,Frequency,Frequency.1,Country,Country.1,Series,Series.1,Source,Source.1,Business line,Business line.1,Time Period,Observation value,Currency,Currency.1,Factor,Factor.1,Type,Type.1,Unit
0,A,Annual,ADD,Advanced Asia Pacific,57100,Premium % of GDP,SR,Swiss Re,SNLIFE,SRNon-life,1991,0.017533,NaN,NaN,0,Units,RATIO,Ratio,NaN
1,A,Annual,ADD,Advanced Asia Pacific,57100,Premium % of GDP,SR,Swiss Re,SNLIFE,SRNon-life,1992,0.017563,NaN,NaN,0,Units,RATIO,Ratio,NaN
2,A,Annual,ADD,Advanced Asia Pacific,57100,Premium % of GDP,SR,Swiss Re,SNLIFE,SRNon-life,1993,0.018787,NaN,NaN,0,Units,RATIO,Ratio,NaN
3,A,Annual,ADD,Advanced Asia Pacific,57100,Premium % of GDP,SR,Swiss Re,SNLIFE,SRNon-life,1994,0.018906,NaN,NaN,0,Units,RATIO,Ratio,NaN
4,A,Annual,ADD,Advanced Asia Pacific,57100,Premium % of GDP,SR,Swiss Re,SNLIFE,SRNon-life,1995,0.019208,NaN,NaN,0,Units,RATIO,Ratio,NaN

In [4]:
sri.describe()

             Series   Time Period  Observation value        Factor  Unit
count  45585.000000  45585.000000       45585.000000  45585.000000   0.0
mean   31653.765120   2013.498475         773.550460      2.220336   NaN
std    22985.309081     12.777810        8049.823313      3.879879   NaN
min    11000.000000   1991.000000          -0.839380      0.000000   NaN
25%    11003.000000   2003.000000           0.023742      0.000000   NaN
50%    11007.000000   2014.000000           0.112606      0.000000   NaN
75%    57200.000000   2025.000000          47.505426      0.000000   NaN
max    57400.000000   2035.000000      376868.589427      9.000000   NaN

In [5]:
sri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45585 entries, 0 to 45584
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Frequency          45585 non-null  object
 1   Frequency.1        45585 non-null  object
 2   Country            45585 non-null  object
 3   Country.1          45585 non-null  object
 4   Series             45585 non-null  int64
 5   Series.1           45585 non-null  object
 6   Source             45585 non-null  object
 7   Source.1           45585 non-null  object
 8   Business line      45585 non-null  object
 9   Business line.1    45585 non-null  object
 10  Time Period        45585 non-null  int64
 11  Observation value  45585 non-null  float64
 12  Currency           18158 non-null  object
 13  Currency.1         18158 non-null  object
 14  Factor             45585 non-null  int64
 15  Factor.1           45585 non-null  object
 16  Type               45540 non-null  object
 17  Type.1             45540 non-null  object
 18  Unit               0 non-null      float64
dtypes: float64(2), int64(3), object(14)
memory usage: 6.6+ MB

In [6]:
sri.columns

Index(['Frequency', 'Frequency.1', 'Country', 'Country.1', 'Series',
       'Series.1', 'Source', 'Source.1', 'Business line', 'Business line.1',
       'Time Period', 'Observation value', 'Currency', 'Currency.1', 'Factor',
       'Factor.1', 'Type', 'Type.1', 'Unit'],
      dtype='object')

In [16]:
sri['Series.1'].unique()

array(['Premium % of GDP', 'Share of world market in %',
       'Insurance density, USD', 'Premium volume in local currency',
       'Premium volume in USD', 'Premium nominal growth',
       'Premium real growth'], dtype=object)